---
repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--diff, --check]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        args: [--strict]

  - repo: local
    hooks:
      - id: pytest-check
        stages: [push]
        types: [python]
        name: pytest-check
        entry: poetry run python -m pytest -v tests/
        language: system
        pass_filenames: false
        always_run: true
