---
default_stages: [commit]
repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.259'
    hooks:
      - id: ruff

  # - repo: https://github.com/pycqa/isort
  #   rev: 5.11.2
  #   hooks:
  #     - id: isort
  #       name: isort (python)
  # Failure to install isort hook
  - repo: local
    hooks:
      - id: isort
        types: [python]
        name: isort
        entry: poetry run python -m isort --check-only .
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--diff, --check]

  # - repo: https://github.com/PyCQA/bandit
  #   rev: '1.7.5'
  #   hooks:
  #     - id: bandit
  #       args: ["-q", "-r", "solver"]
  - repo: https://github.com/python-poetry/poetry
    rev: '1.4.0'  # add version here
    hooks:
      - id: poetry-check
      # - id: poetry-lock
      #   args: ["--no-update"]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.1.1
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: ['numpy.typing.mypy_plugin']
  #       args: [--strict]
  #
  # Would use the one above but the hook uses it's own venv of mypy and I need to figure out how to configure plugins
  - repo: local
    hooks:
      - id: mypy
        types: [python]
        name: mypy
        entry: poetry run python -m mypy --strict .
        language: system
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: pytest-check
        stages: [push]
        types: [python]
        name: pytest-check
        entry: poetry run python -m pytest -v tests/
        language: system
        pass_filenames: false
        always_run: true
